version: '3.8'

services:
  db:
    container_name: postgresql
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - mydata:/var/lib/postgresql/data

volumes:
  mydata:
